# Generated by Django 2.2 on 2019-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputeventusercomment',
            name='send_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inputeventimage',
            name='send_status',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
