# Generated by Django 2.2 on 2019-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mokrug',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
