# Generated by Django 2.2 on 2019-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0002_auto_20190706_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputevent',
            name='send_status',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
