# Generated by Django 2.2 on 2019-05-17 13:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0002_auto_20190505_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputeventimage',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
        migrations.AlterField(
            model_name='inputeventimage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
