# Generated by Django 2.2 on 2019-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0002_auto_20190420_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='region',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
