# Generated by Django 2.2 on 2019-05-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0003_auto_20190517_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputeventimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='paradox.InputEvent'),
        ),
    ]
