# Generated by Django 2.2 on 2019-04-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0003_auto_20190420_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputevent',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='inputevent',
            name='region',
            field=models.CharField(max_length=6),
        ),
    ]
