# Generated by Django 2.2 on 2019-05-18 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0004_auto_20190517_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputeventimage',
            options={'ordering': ('time_created',)},
        ),
        migrations.AlterModelOptions(
            name='inputeventusercomment',
            options={'ordering': ('time_created',)},
        ),
        migrations.RenameField(
            model_name='inputevent',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='inputevent',
            old_name='complaint_status',
            new_name='uik_complaint_status',
        ),
        migrations.RenameField(
            model_name='inputeventimage',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='inputeventusercomment',
            old_name='timestamp',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='inputeventimage',
            name='uuid',
        ),
        migrations.AddField(
            model_name='inputeventimage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputeventimage',
            name='time_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inputeventimage',
            name='time_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
