# Generated by Django 2.2 on 2019-04-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0004_auto_20190420_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolInputEvent',
            fields=[
                ('inputevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paradox.InputEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('paradox.inputevent',),
        ),
        migrations.CreateModel(
            name='IntegerInputEvent',
            fields=[
                ('inputevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paradox.InputEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('paradox.inputevent',),
        ),
        migrations.RemoveField(
            model_name='inputevent',
            name='value',
        ),
    ]
