# Generated by Django 2.2 on 2019-04-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0005_auto_20190424_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolinputevent',
            name='value',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='integerinputevent',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
