# Generated by Django 2.2.3 on 2019-12-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0008_auto_20190824_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputeventusercomment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='paradox.InputEvent'),
        ),
    ]
