# Generated by Django 2.2.3 on 2019-12-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0009_auto_20191220_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integerinputevent',
            name='inputevent_ptr',
        ),
        migrations.DeleteModel(
            name='BoolInputEvent',
        ),
        migrations.DeleteModel(
            name='IntegerInputEvent',
        ),
    ]
