# Generated by Django 2.2.3 on 2020-04-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0020_auto_20200305_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinator',
            new_name='Organization',
        ),
        migrations.AlterField(
            model_name='answer',
            name='tik_complaint_status',
            field=models.CharField(choices=[('none', 'не подавалась'), ('sending_to_moderator', 'отправляется модератору'), ('moderating', 'ожидает модерации'), ('denied', 'отклонено'), ('email_sent', 'email отправлен')], default='none', max_length=30),
        ),
    ]
