# Generated by Django 2.2.3 on 2019-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0003_auto_20190706_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputevent',
            name='tik_complaint_status',
            field=models.CharField(choices=[('none', 'не подавалась'), ('refuse_to_accept', 'отказ принять жалобу'), ('refuse_to_resolve', 'отказ рассмотрения жалобы'), ('waiting_reply', 'ожидание решения комиссии'), ('got_unfair_reply', 'получено неудовлетворительное решение'), ('got_fair_reply', 'получено удовлетворительное решение')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
