# Generated by Django 2.2.3 on 2019-12-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0010_auto_20191220_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputEvent',
            new_name='Answer',
        ),
    ]
