# Generated by Django 2.2.3 on 2019-12-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0012_auto_20191220_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputEventImage',
            new_name='AnswerImage',
        ),
        migrations.RenameModel(
            old_name='InputEventUserComment',
            new_name='AnswerUserComment',
        ),
    ]
