# Generated by Django 2.2.3 on 2019-12-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0014_auto_20191220_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='input_label',
            new_name='question_label',
        ),
    ]
