# Generated by Django 2.2.3 on 2019-12-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0015_auto_20191220_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boolanswer',
            old_name='value',
            new_name='rawvalue',
        ),
        migrations.RenameField(
            model_name='integeranswer',
            old_name='value',
            new_name='rawvalue',
        ),
    ]
