# Generated by Django 2.2.3 on 2019-12-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0016_auto_20191223_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='mokrug',
            new_name='munokrug',
        ),
    ]
