# Generated by Django 2.2.3 on 2019-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0017_auto_20191228_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='munokrug',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
