# Generated by Django 2.2.3 on 2020-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0018_auto_20191228_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='elections_name',
            field=models.TextField(null=True),
        ),
    ]
