# Generated by Django 2.2.3 on 2020-03-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0019_campaign_elections_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='alarm',
            new_name='is_incident',
        ),
    ]
