# Generated by Django 2.2.3 on 2020-04-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0021_auto_20200404_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='elections_name',
            new_name='election_name',
        ),
    ]
