# Generated by Django 2.2.3 on 2020-04-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0022_auto_20200404_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='fromtime',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='totime',
        ),
    ]
