# Generated by Django 2.2.3 on 2020-05-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0023_auto_20200430_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='external_channels',
            new_name='contacts',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='phones',
        ),
    ]
