# Generated by Django 2.2.3 on 2020-05-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0024_auto_20200501_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='external_channels',
            new_name='contacts',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phones',
        ),
    ]
