name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Testing:
    env:
      PYTHONDEVMODE: 1
      PYTHONWARNINGS: "ignore"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12.6"]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Versions
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          allow-prereleases: true

      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
      - name: Install PDM via pip
        run: python -m pip install pdm

      - name: Install Dev Dependencies
        run: |
          pdm install -v --group test --lockfile ci.lock
          pdm run pip install -U setuptools
          pdm info
      - name: Run Tests
        run: pdm run pytest --doctest-modules -n auto --cov --cov-config=.coveragerc --cov-report=xml

      # - name: Upload results to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml
